"""making adjustment to order table

Revision ID: 5ee88bf9455e
Revises: d95729950daa
Create Date: 2024-09-02 16:44:18.272870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee88bf9455e'
down_revision: Union[str, None] = 'd95729950daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
