"""Add new column to orderitem table

Revision ID: d95729950daa
Revises: 
Create Date: 2024-08-30 12:31:35.584946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95729950daa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orderitem_product_category_id_productcategory_id', 'productcategory', ['product_category_id'], ['id'])
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderitem_product_category_id_productcategory_id', type_='foreignkey')
        # ### end Alembic commands ###
